[tool.black]
exclude = 'opensafely/_vendor'

[tool.vendoring]
destination = "opensafely/_vendor/"
requirements = "vendor.txt"
namespace = "opensafely._vendor"

# We don't use any patches, but this directory has to be defined (though it
# doesn't have to exist)
patches-dir = "patches"
# Other config values which have to be defined even though we don't use them
protected-files = []
license.directories = {}
license.fallback-urls = {}

[tool.vendoring.transformations]
# Imports of the from `import X.Y` can't be rewritten automatically by the
# vendoring tool so we apply some basic replacements here
substitute = [
  { match='import ruamel\.yaml', replace="from ruamel import yaml as ruamel_yaml" },
  { match='from ruamel\.yaml', replace="from TEMP_ruamel.yaml" },
  { match=' ruamel\.yaml', replace=" ruamel_yaml" },
  { match='from TEMP_ruamel\.yaml', replace="from ruamel.yaml" },
]
drop = [
  # ruamel.yaml creates this and I don't think we need it
  "*-nspkg.pth",
]

[tool.vendoring.typing-stubs]
# Prevents us geneating `*.pyi` files which I don't think we need
jobrunner = []
ruamel = []
