name: Tests

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Run test suite
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        pip install -r requirements.dev.txt
    - name: Run tests
      run: python -m pytest

  test-package-build:
    runs-on: ubuntu-latest
    name: Test we can build PyPI package
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Build package
      run: |
        pip install wheel
        python setup.py sdist bdist_wheel
    - name: Check that sdist installs
      run: |
        python -m venv test-sdist
        test-sdist/bin/pip install dist/*.tar.gz
    - name: Check that the wheel installs
      run: |
        pip install dist/opensafely-*.whl
    - name: Run smoketest
      run: |
        opensafely run --help
